services:
    backend:
        build:
            args:
                - NODE_ENV=development
            context: backend
            target: dev-envs
        command: npm run start-watch
        ports:
            - 8080:8080
        secrets:
            - db-password
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - public
            - private
        depends_on:
            - db
    db:
        image: postgres:14.1-alpine
        restart: always
        secrets:
            - db-password
        volumes:
            - ./db/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
            - db-data:/var/lib/postgresql/data
        networks:
            - private
        environment:
            - POSTGRES_DB=example
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    frontend:
        build:
            context: frontend
            target: dev-envs
        ports:
            - 3000:3000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - public
        depends_on:
            - backend
networks:
    public:
    private:
volumes:
    back-notused:
    db-data:
secrets:
    db-password:
        file: db/password.txt
